export const UPDATE_PERSONAL = "UPDATE_PERSONAL";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const LOCAL_STORAGE_BACKUP = "LOCAL_STORAGE_BACKUP";
export const EDIT_EDUCATION = "EDIT_EDUCATION";